pluginManagement {
    repositories {
        maven {
            name = 'CleanroomMC'
            url = 'https://maven.cleanroommc.com'
        }
        gradlePluginPortal()
    }
}

plugins {
    // Adds the CleanroomMC, Minecraft libraries, Maven Central and local Maven repositories to every project
    id 'com.cleanroommc.cleanroomgradle.settings' version '0.17.5'
    // Automatic toolchain provisioning
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

// Due to an IntelliJ bug, this has to be done
// rootProject.name = archives_base_name
rootProject.name = rootProject.projectDir.getName()
